fix: new stable repo url for helm2
CircleCI-Public/helm-orb pull request #35
Opened 2020-12-22 11:12 UTC by vhemt

### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

### Description

2020-12-23 16:34 UTC, dsayling requested changes

2020-12-23 16:34 UTC, dsayling commented on src/commands/install-helm-client.yml
> +          helm init --client-only --stable-repo-url https://charts.helm.sh/stable
Would you object to making the URL a parameter to the command? Something like `v2stable_repo_url` with this as the default? Per their [blog post](https://helm.sh/blog/new-location-stable-incubator-charts/), some may be suing their own hosted helm repos.

2020-12-24 10:03 UTC, vhemt commented on src/commands/install-helm-client.yml
> +          helm init --client-only --stable-repo-url https://charts.helm.sh/stable
done, let me know if it looks good for you :)

2020-12-29 15:07 UTC, dsayling approved these changes

2020-12-29 15:07 UTC, merged

2020-12-29 18:13 UTC, fulaphex commented
when will this be released? until then, helm client installs are broken for helm v2

2020-12-29 19:23 UTC, dsayling commented
@fulaphex apologies, I was not aware auto-releasing on this orb is not configured. The release should be complete as `1.2.0` now