migration 0.0.1
CircleCI-Public/helm-orb pull request #49
Opened 2022-04-25 16:55 UTC by JalexChen

### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

Helm 2 has been deprecated and no longer supported, therefore the tests and the commands associated with version 2 have been removed; helm 3's latest version is the default for commands now

Additionally, this was now migrated over to orb tools 11

### Description

Removed helm 2 tests and commands + migrated over to orb tools 11

2022-04-26 16:45 UTC, EricRibeiro requested changes

2022-04-26 16:45 UTC, EricRibeiro commented on .circleci/test-deploy.yml
> +    default: "dev:alpha"
These lines should not be necessary for the Orb Tools 11. They are remnants of the previous version.

2022-04-26 16:45 UTC, EricRibeiro commented on .circleci/test-deploy.yml
> +  kubernetes: circleci/kubernetes@0.2.0
These two orbs are outdated. Can you try updating them?

If it breaks the test, please open an issue so the team can work on it later.

2022-04-26 16:45 UTC, EricRibeiro commented on .circleci/test-deploy.yml
> +  queue: eddiewebb/queue@1.1.2
Same as above.

2022-04-26 18:02 UTC, JalexChen commented on src/@orb.yml
>    kubernetes: circleci/kubernetes@0.2.0
yes, the source url is required and i believe it's supposed to point towards the github, which is what the node orb does as well: https://circleci.com/developer/orbs/orb/circleci/node

2022-04-26 18:06 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/helm?version=dev:146367908e08650bfaf09a5523b4789af528b12b

2022-04-26 18:11 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/helm?version=dev:a073c9d5a656547fa8d79acb6ee22582df289973

2022-04-26 21:16 UTC, EricRibeiro commented on .circleci/test-deploy.yml
> +          exclude: RC005,RC009
Any particular reasons for these exclusions?

2022-04-27 17:37 UTC, JalexChen commented on .circleci/test-deploy.yml
> +          exclude: RC005,RC009
@EricRibeiro RC005 was due to the orb description not being long enough even though it was what was used previously, and RC009 was since one of the helm2 commands did not work when imported as a script. RC009 should be a non-factor now since helm2 was removed, but i think RC005 should still be excluded

2022-04-29 15:18 UTC, EricRibeiro commented on .circleci/test-deploy.yml
> +          exclude: RC005,RC009
With the version support bit you included, you have 90 characters in the orb description. RC005 complains if you have less than 64. You can safely remove it from the exclusion list.

If what is triggering RC009 isn't a problem anymore, can we try removing it too?

2022-04-29 15:26 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/helm?version=dev:b71317a4cbd06a7d14340a789d9b6a048b322dc1

2022-04-29 18:14 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/helm?version=dev:85449d9a1bd4a20ab3c37044ad795b891351069e

2022-05-02 17:34 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/helm?version=dev:695ceb1cda6571a36b441610f99737cea4a84197

2022-05-02 17:37 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/helm?version=dev:4f90223814debdfd8eaa03925ae873aa5f30f3c6

2022-05-02 18:19 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/helm?version=dev:6daaf14d154367bf201613f4dff440982af2b239

2022-05-02 18:55 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/helm?version=dev:989b9ec53f634c29ea44f58e9141149f14e1a121

2022-05-02 18:57 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/helm?version=dev:b00529f9b09554600034cf070af6021e0e2759e6

2022-05-02 19:41 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/helm?version=dev:cf5f571d666df027444e08a6a2c37945515e3512

2022-05-02 20:18 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/helm?version=dev:d1a6b02bd0c074a4bafae3c74cca83ae3fae092b

2022-05-02 22:07 UTC, EricRibeiro approved these changes

2022-05-02 22:08 UTC, merged

2022-05-02 22:09 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/helm?version=dev:38579cd19a9ac530c450b67f02adbaff49f39697

2022-05-02 22:12 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/helm?version=dev:38579cd19a9ac530c450b67f02adbaff49f39697

2022-05-02 23:18 UTC, orb-publisher commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/helm?version=dev:38579cd19a9ac530c450b67f02adbaff49f39697

2022-05-02 23:46 UTC, orb-publisher commented
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/helm?version=2.0.0